/* ==========================================================================
   Variation F -- "Concrete (Neo-Brutalist)"
   Curated book catalogue (a distinct subset of the shared Open Library data).
   Genres: Science, Psychology, Philosophy, Science Fiction, Thriller, Mystery, Fantasy
   52 titles. Plain global (no modules -- must run from file://).
   ========================================================================== */

const BOOKS = [
  {
    id: "ol-OL1892618W",
    title: "A Briefer History of Time",
    subtitle: "",
    author: "Stephen Hawking",
    year: 2005,
    genre: "Science",
    rating: 3.7,
    pages: 176,
    publisher: "Bantam Dell Pub Group",
    language: "Russian",
    isbn: "8377852969",
    cover: "assets/covers/ol-OL1892618W.jpg",
    coverFrom: "#5f0b65",
    coverTo: "#340637",
    tags: ["cosmology", "science / cosmology", "science", "nonfiction"],
    blurb: ["The science classic made more accessible and more concise. Illustrated. Updated with new research.Stephen Hawking's worldwide bestseller, A Brief History of Time, has been a landmark volume in scientific writing. Its author's engaging voice is one reason, and the compelling subjects he addresses is another: the nature of space and time, the role of God in creation, the history and future of the universe."],
    quote: null
  },
  {
    id: "ol-OL8461625W",
    title: "A-level physics",
    subtitle: "",
    author: "Roger Muncaster",
    year: 1981,
    genre: "Science",
    rating: null,
    pages: 953,
    publisher: "Thornes",
    language: "English",
    isbn: "0748717390",
    cover: "assets/covers/ol-OL8461625W.jpg",
    coverFrom: "#0c6462",
    coverTo: "#073636",
    tags: ["physics", "problems", "textbooks"],
    blurb: ["A-level physics is a science work by Roger Muncaster, first published in 1981. The edition catalogued here runs to 953 pages. It was published by Thornes.", "Open Library catalogues it under physics, problems and textbooks. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL16025198W",
    title: "Active physics",
    subtitle: "",
    author: "Arthur Eisenkraft",
    year: 1998,
    genre: "Science",
    rating: 4.3,
    pages: 332,
    publisher: "It's About Time, Inc, Herf Jones Education Division",
    language: "English",
    isbn: "1891629077",
    cover: "assets/covers/ol-OL16025198W.jpg",
    coverFrom: "#64310d",
    coverTo: "#361b07",
    tags: ["textbooks", "science", "physics textbooks", "science textbooks"],
    blurb: ["6 v. : ill.; 27 cm + teacher's edition (6 v. : ill. ; 28 cm)"],
    quote: null
  },
  {
    id: "ol-OL10483518W",
    title: "Advanced Level Physics",
    subtitle: "",
    author: "Michael Nelkon",
    year: 1958,
    genre: "Science",
    rating: 3.8,
    pages: 1079,
    publisher: "Heinemann Educational Books",
    language: "English",
    isbn: "9780435923037",
    cover: "assets/covers/ol-OL10483518W.jpg",
    coverFrom: "#436907",
    coverTo: "#253904",
    tags: ["physics", "textbooks", "problems", "literary collections"],
    blurb: ["Advanced Level Physics is a science work by Michael Nelkon, first published in 1958. The edition catalogued here runs to 1079 pages. It was published by Heinemann Educational Books.", "Open Library catalogues it under physics, textbooks and problems. Readers there give it an average rating of 3.8 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL2698159W",
    title: "An introduction to the physics of nuclei and particles",
    subtitle: "",
    author: "R. A. Dunlap",
    year: 2003,
    genre: "Science",
    rating: null,
    pages: 284,
    publisher: "Thomson/Brooks-Cole",
    language: "English",
    isbn: "0534392946",
    cover: "assets/covers/ol-OL2698159W.jpg",
    coverFrom: "#620e4c",
    coverTo: "#350829",
    tags: ["nuclear physics", "physics", "science"],
    blurb: ["An introduction to the physics of nuclei and particles is a science work by R. A. Dunlap, first published in 2003. The edition catalogued here runs to 284 pages. It was published by Thomson/Brooks-Cole.", "Open Library catalogues it under nuclear physics, physics and science. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL1879309W",
    title: "Applied physics",
    subtitle: "",
    author: "Dale Ewen",
    year: 1997,
    genre: "Science",
    rating: null,
    pages: 753,
    publisher: "Prentice Hall",
    language: "English",
    isbn: "9780134159386",
    cover: "assets/covers/ol-OL1879309W.jpg",
    coverFrom: "#515818",
    coverTo: "#2c300d",
    tags: ["textbooks", "physics", "physics.", "applied physics"],
    blurb: ["Applied physics is a science work by Dale Ewen, first published in 1997. The edition catalogued here runs to 753 pages. It was published by Prentice Hall.", "Open Library catalogues it under textbooks, physics and physics.. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL342141W",
    title: "Atomic physics",
    subtitle: "",
    author: "J. B. Rajam",
    year: 1966,
    genre: "Science",
    rating: 4.4,
    pages: 1279,
    publisher: "S. Chand",
    language: "English",
    isbn: "",
    cover: "assets/covers/ol-OL342141W.jpg",
    coverFrom: "#30145d",
    coverTo: "#1a0b33",
    tags: ["nuclear physics", "physics", "science"],
    blurb: ["Atomic physics is a science work by J. B. Rajam, first published in 1966. The edition catalogued here runs to 1279 pages. It was published by S. Chand.", "Open Library catalogues it under nuclear physics, physics and science. Readers there give it an average rating of 4.4 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL2719370W",
    title: "Basic physics",
    subtitle: "",
    author: "Karl F. Kuhn",
    year: 1979,
    genre: "Science",
    rating: null,
    pages: 323,
    publisher: "J. Wiley",
    language: "English",
    isbn: "0471134473",
    cover: "assets/covers/ol-OL2719370W.jpg",
    coverFrom: "#0b3d66",
    coverTo: "#062137",
    tags: ["textbooks", "physics textbooks", "science textbooks", "physics"],
    blurb: ["Basic physics is a science work by Karl F. Kuhn, first published in 1979. The edition catalogued here runs to 323 pages. It was published by J. Wiley.", "Open Library catalogues it under textbooks, physics textbooks and science textbooks. This record describes the English edition."],
    quote: { text: "Physics deals with quantities that can be measured.", source: "First sentence" }
  },
  {
    id: "ol-OL1892033W",
    title: "A little book on the human shadow",
    subtitle: "",
    author: "Robert Bly",
    year: 1986,
    genre: "Psychology",
    rating: null,
    pages: 81,
    publisher: "Raccoon Books",
    language: "English",
    isbn: "0062548476",
    cover: "assets/covers/ol-OL1892033W.jpg",
    coverFrom: "#65580b",
    coverTo: "#373006",
    tags: ["psychoanalysis", "psychology"],
    blurb: ["A little book on the human shadow is a psychology work by Robert Bly, first published in 1986. The edition catalogued here runs to 81 pages. It was published by Raccoon Books.", "Open Library catalogues it under psychoanalysis and psychology. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL25742643W",
    title: "A Macat Analysis of Daniel Kahneman's Thinking, Fast and Slow",
    subtitle: "",
    author: "Jacqueline Allan",
    year: 2018,
    genre: "Psychology",
    rating: 4,
    pages: null,
    publisher: "Taylor & Francis Group",
    language: "English",
    isbn: "1912453053",
    cover: "assets/covers/ol-OL25742643W.jpg",
    coverFrom: "#5e3d12",
    coverTo: "#33210a",
    tags: ["psychology"],
    blurb: ["A Macat Analysis of Daniel Kahneman's Thinking, Fast and Slow is a psychology work by Jacqueline Allan, first published in 2018. It was published by Taylor & Francis Group.", "Open Library catalogues it under psychology. Readers there give it an average rating of 4.0 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL1941879W",
    title: "A Primer of Freudian Psychology",
    subtitle: "",
    author: "Calvin S. Hall",
    year: 1954,
    genre: "Psychology",
    rating: 3.7,
    pages: 129,
    publisher: "Creative Media Partners, LLC",
    language: "English",
    isbn: "1013802802",
    cover: "assets/covers/ol-OL1941879W.jpg",
    coverFrom: "#083a68",
    coverTo: "#041f39",
    tags: ["psychoanalysis", "textbooks", "personnalité", "psychoanalyse"],
    blurb: ["The purpose of this primer is to present clearly, briefly, and systematically the psychological theories advanced by Sigmund Freud. Freud's contributions in the areas of abnormal psychology, psychopathology, psychotherapy, and psychiatry have been summarized by a number of writers, but his work as a psychological theorist in the area of general psychology has not been presented in a systematic and comprehensive form. The author contends that Freud's distinctive role in intellectual and scientific history is that of a psychological theorist."],
    quote: { text: "Although Sigmund Freud was born in Freiberg, Moravia, and died in London, England, he belongs to Vienna, where he lived for nearly eighty years.", source: "First sentence" }
  },
  {
    id: "ol-OL1941876W",
    title: "A Primer of Jungian Psychology",
    subtitle: "",
    author: "Calvin S. Hall",
    year: 1973,
    genre: "Psychology",
    rating: 3.8,
    pages: 142,
    publisher: "Croom Helm Ltd",
    language: "English",
    isbn: "0451620674",
    cover: "assets/covers/ol-OL1941876W.jpg",
    coverFrom: "#6a0f06",
    coverTo: "#3a0803",
    tags: ["textbooks", "jungian psychology", "psychology textbooks", "humanities textbooks"],
    blurb: ["\"Carl Jung's contributions to our understanding of the human psyche have made him one of the most significant figures in the field of analytical psychology."],
    quote: null
  },
  {
    id: "ol-OL1069166W",
    title: "Abriss der Psychoanalyse",
    subtitle: "",
    author: "Sigmund Freud",
    year: 1949,
    genre: "Psychology",
    rating: null,
    pages: 84,
    publisher: "Fischer Bücherei",
    language: "German",
    isbn: "0701201231",
    cover: "assets/covers/ol-OL1069166W.jpg",
    coverFrom: "#076935",
    coverTo: "#04391d",
    tags: ["nonfiction", "psicoanálisis", "psychoanalysis", "psychology"],
    blurb: ["One of fifteen volumes in the new Freud series commissioned for Penguin by series editor Adam Phillips.  Part of a plan to generate a new, non-specialist Freud for a wide readership, which goes way beyond the institutional/clinical market and presents material to the reader in a new way. This volume will contain NEW INTRODUCTORY LECTURES IN PSYCHOANALYSIS and AN OUTLINE OF PSYCHOANALYSIS."],
    quote: { text: "Psycho-analysis makes a basic assumption, the discussion of which is reserved to philosophical thought but the justification for which lies in its results.", source: "First sentence" }
  },
  {
    id: "ol-OL95164W",
    title: "Analytical psychology",
    subtitle: "",
    author: "Carl Gustav Jung",
    year: 1916,
    genre: "Psychology",
    rating: null,
    pages: 224,
    publisher: "Routledge",
    language: "English",
    isbn: "9780548155059",
    cover: "assets/covers/ol-OL95164W.jpg",
    coverFrom: "#4a610f",
    coverTo: "#283508",
    tags: ["psychoanalysis", "jungian psychology", "psychology"],
    blurb: ["Analytical psychology is a psychology work by Carl Gustav Jung, first published in 1916. The edition catalogued here runs to 224 pages. It was published by Routledge.", "Open Library catalogues it under psychoanalysis, jungian psychology and psychology. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL17930368W",
    title: "Atomic Habits",
    subtitle: "",
    author: "James Clear",
    year: 2016,
    genre: "Psychology",
    rating: 4,
    pages: 322,
    publisher: "Avery, an Imprint of Penguin Random House LLC",
    language: "French",
    isbn: "6052998385",
    cover: "assets/covers/ol-OL17930368W.jpg",
    coverFrom: "#066a56",
    coverTo: "#033a2f",
    tags: ["habit", "habit breaking", "behavior modification", "business"],
    blurb: ["No matter your goals, Atomic Habits offers a proven framework for improving every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results. Atomic Habits pdf"],
    quote: null
  },
  {
    id: "ol-OL16929630W",
    title: "Attached",
    subtitle: "",
    author: "Amir Levine",
    year: 2010,
    genre: "Psychology",
    rating: 4.2,
    pages: 294,
    publisher: "Tarcher",
    language: "English",
    isbn: "1585428485",
    cover: "assets/covers/ol-OL16929630W.jpg",
    coverFrom: "#175919",
    coverTo: "#0d310e",
    tags: ["attachment behavior", "intimacy (psychology)", "psychology"],
    blurb: ["Introduces the theory of adult attachment as an advanced relationship science that can enable individuals to find and sustain love, offering insight into the roles of genetics and early family life in how people approach relationships."],
    quote: null
  },
  {
    id: "ol-OL17837119W",
    title: "12 Rules for Life",
    subtitle: "",
    author: "Jordan B. Peterson",
    year: 2015,
    genre: "Philosophy",
    rating: 3.8,
    pages: 480,
    publisher: "Planeta",
    language: "English",
    isbn: "9780345816023",
    cover: "assets/covers/ol-OL17837119W.jpg",
    coverFrom: "#255a16",
    coverTo: "#14310c",
    tags: ["conduct of life", "philosophy", "philosophy / social", "psychology"],
    blurb: ["Duplicate of"],
    quote: null
  },
  {
    id: "ol-OL1088357W",
    title: "A History of Western Philosophy",
    subtitle: "",
    author: "Bertrand Russell",
    year: 1945,
    genre: "Philosophy",
    rating: 4.2,
    pages: 895,
    publisher: "Routledge",
    language: "English",
    isbn: "9780041000450",
    cover: "assets/covers/ol-OL1088357W.jpg",
    coverFrom: "#145b5c",
    coverTo: "#0b3232",
    tags: ["western influences", "philosophy", "political science", "history"],
    blurb: ["[The author's] purpose is to exhibit philosophy as an integral part of social and political life: not as the isolated speculations of remarkable individuals, but as both an effect and a cause of the character of the various communities in which different systems flourished.-Pref."],
    quote: { text: "IN all history, nothing is so surprising or so difficult to account for as the sudden rise of civilization in Greece.", source: "First sentence" }
  },
  {
    id: "ol-OL98130W",
    title: "Also sprach Zarathustra",
    subtitle: "Ein Buch für Alle und Keinen",
    author: "Friedrich Nietzsche",
    year: 1883,
    genre: "Philosophy",
    rating: 4.1,
    pages: 354,
    publisher: "Insel Verlag GmbH",
    language: "English",
    isbn: "1544783892",
    cover: "assets/covers/ol-OL98130W.jpg",
    coverFrom: "#14205c",
    coverTo: "#0b1232",
    tags: ["classic literature", "fiction", "filosofie", "filosofía"],
    blurb: ["A landmark work of philosophy and of literature, Thus Spoke Zarathustra is the fullest expression of Nietzche's belief that \"the object of mankind should lie in its highest individuals.\" In his thirtieth year Zarathustra - the archetypal Ubermensch representative of supreme passion and creativity - abandons his home for the mountains, where he lives, literally and figuratively, on a level of experience far above the conventional standards of good and evil. The exuberant, poetic testimony of Nietzche's great messianic hero (and alter ego) is a vivid demonstration of the philosopher's genius."],
    quote: { text: "When Zarathustra was thirty years old, he left his home and the lake of his home, and went into the mountains.", source: "First sentence" }
  },
  {
    id: "ol-OL21686956W",
    title: "Be Water, My Friend",
    subtitle: "",
    author: "Shannon Lee",
    year: 2020,
    genre: "Philosophy",
    rating: null,
    pages: 240,
    publisher: "Dojo Ediciones",
    language: "English",
    isbn: "1250794838",
    cover: "assets/covers/ol-OL21686956W.jpg",
    coverFrom: "#572b19",
    coverTo: "#30170e",
    tags: ["philosophy", "recreation"],
    blurb: ["Be Water, My Friend is a philosophy work by Shannon Lee, first published in 2020. The edition catalogued here runs to 240 pages. It was published by Dojo Ediciones.", "Open Library catalogues it under philosophy and recreation. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL5814581W",
    title: "Bluets",
    subtitle: "",
    author: "Maggie Nelson",
    year: 2009,
    genre: "Philosophy",
    rating: 4,
    pages: 112,
    publisher: "Wave Books",
    language: "English",
    isbn: "1911214527",
    cover: "assets/covers/ol-OL5814581W.jpg",
    coverFrom: "#611038",
    coverTo: "#35091f",
    tags: ["blue", "color (philosophy)", "philosophy"],
    blurb: ["Bluets is a philosophy work by Maggie Nelson, first published in 2009. The edition catalogued here runs to 112 pages. It was published by Wave Books.", "Open Library catalogues it under blue, color (philosophy) and philosophy. Readers there give it an average rating of 4.0 out of 5. This record describes the English edition."],
    quote: null
  },
  {
    id: "ol-OL15236125W",
    title: "Chto takoe iskusstvo? / What is art?",
    subtitle: "",
    author: "Лев Толстой",
    year: 1898,
    genre: "Philosophy",
    rating: null,
    pages: 237,
    publisher: "H. Altemus",
    language: "English",
    isbn: "9780735102934",
    cover: "assets/covers/ol-OL15236125W.jpg",
    coverFrom: "#1a6709",
    coverTo: "#0e3805",
    tags: ["art", "art and morals", "arts", "arts and morals"],
    blurb: ["Marathi translation of the what is art?, English translation by Charles Johnston from Russian."],
    quote: null
  },
  {
    id: "ol-OL1183657W",
    title: "Die Welt als Wille und Vorstellung",
    subtitle: "",
    author: "Arthur Schopenhauer",
    year: 1819,
    genre: "Philosophy",
    rating: null,
    pages: 514,
    publisher: "Paul, Trench, Trübner",
    language: "German",
    isbn: "8477203903",
    cover: "assets/covers/ol-OL1183657W.jpg",
    coverFrom: "#680852",
    coverTo: "#39042d",
    tags: ["philosophy", "will", "idea (philosophy)", "theory of knowledge"],
    blurb: ["The German philosopher explains his thoughts about intellectual perception and abstract representation and critically analyzes Kant's ideas and teachings. Bibliogs."],
    quote: { text: "O mundo é a minha representação.", source: "First sentence" }
  },
  {
    id: "ol-OL1151518W",
    title: "Discours de la méthode",
    subtitle: "",
    author: "René Descartes",
    year: 1644,
    genre: "Philosophy",
    rating: 4.2,
    pages: 182,
    publisher: "Hachette Littérature",
    language: "Spanish",
    isbn: "0872201732",
    cover: "assets/covers/ol-OL1151518W.jpg",
    coverFrom: "#5a1b16",
    coverTo: "#310f0c",
    tags: ["methodology", "science", "modern philosophy", "early works to 1800"],
    blurb: ["By an almost universal agreement among philosophers and historians, Rene' Descartes is considered the originator of modern philosophy, or at least the first important philosopher of our times. If we add to this the common belief that philosophy points the way for developments in all other fields, it will be evident that to Descartes is ascribed an importance comparable to that of the beginnings of intellectual culture in Greece or of the origin and spread of Christianity in the Mediterranean regions, and surpassing all other events in history."],
    quote: { text: "Good sense is the best distributed thing in the world, for everyone thinks himself to be so well endowed with it that even those who are the most difficult to please in everything else are not at all wont to desire more of it than they have.", source: "First sentence" }
  },
  {
    id: "ol-OL17365W",
    title: "2001",
    subtitle: "A Space Odyssey",
    author: "Arthur C. Clarke",
    year: 1968,
    genre: "Science Fiction",
    rating: 4.2,
    pages: 237,
    publisher: "Debolsillo",
    language: "English",
    isbn: "8485752643",
    cover: "assets/covers/ol-OL17365W.jpg",
    coverFrom: "#660a46",
    coverTo: "#380526",
    tags: ["computers", "fiction", "science fiction", "twenty-first century"],
    blurb: ["A novel that proposes an idea about how the human race might have begun and where it might be headed...given a little help from out there. A colaboration of ideas with director Stanley Kubrick in the late 1960's it begins at \"the dawn of man\" and then leaps to the year 2001 where a mission to Saturn (Jupiter in the film) is mounted to try and answer questions raised by the discovery of an ancient artifact dug up on the moon. Though not particularly fast paced, the science is good, and there are a few hair raising events."],
    quote: { text: "Behind every man now alive stand thirty ghosts, for that is the ratio by which the dead outnumber the living.", source: "First sentence" }
  },
  {
    id: "ol-OL17391W",
    title: "2010, odyssey two",
    subtitle: "",
    author: "Arthur C. Clarke",
    year: 1982,
    genre: "Science Fiction",
    rating: 3.8,
    pages: 304,
    publisher: "Granada Publishing Ltd(england",
    language: "English",
    isbn: "0586056998",
    cover: "assets/covers/ol-OL17391W.jpg",
    coverFrom: "#102360",
    coverTo: "#091334",
    tags: ["interplanetary voyages", "fiction", "science fiction", "exploration"],
    blurb: ["When 2001: A Space Odyssey first shocked, amazed, and delighted millions in the late 1960s, the novel was quickly recognized as a classic. Since then, its fame has grown steadily among the multitudes who have read the novel or seen the film based on it. Yet, along with almost universal acclaim, a host of questions has grown more insistent through the years:", "Who or what transformed Dave Bowman into the Star-Child? What purpose lay behind the transformation? What would become of the Star-Child?"],
    quote: { text: "EVEN IN THIS METRIC AGE, IT WAS STILL THE THOUsand-foot telescope, not the three-hundred-meter one.", source: "First sentence" }
  },
  {
    id: "ol-OL17897265W",
    title: "A Closed and Common Orbit",
    subtitle: "",
    author: "Becky Chambers",
    year: 2016,
    genre: "Science Fiction",
    rating: 4.2,
    pages: 416,
    publisher: "Hodder & Stoughton",
    language: "English",
    isbn: "1515966429",
    cover: "assets/covers/ol-OL17897265W.jpg",
    coverFrom: "#200b65",
    coverTo: "#120637",
    tags: ["fiction in english", "science fiction", "fiction"],
    blurb: ["Once, Lovelace had eyes and ears everywhere. She was a ship's artificial intelligence system - possessing a personality and very human emotions. But when her ship was badly damaged, Lovelace was forced to reboot and reset. Now housed in an illegal synthetic body, she's never felt so isolated.", "But Lovelace is not alone. Pepper, an engineer who risked her life to reinstall Lovelace's program, has remained by her side and is determined to help her."],
    quote: null
  },
  {
    id: "ol-OL1975705W",
    title: "A Deepness in the Sky (Zones of Thought)",
    subtitle: "",
    author: "Vernor Vinge",
    year: 1999,
    genre: "Science Fiction",
    rating: 4.4,
    pages: 792,
    publisher: "Orion Publishing Group, Limited",
    language: "English",
    isbn: "1857988515",
    cover: "assets/covers/ol-OL1975705W.jpg",
    coverFrom: "#4c5818",
    coverTo: "#2a300d",
    tags: ["life on other planets", "fiction", "science fiction", "hugo award winner"],
    blurb: ["From inside cover Tor First Edition March 1999:", "Thirty thousand years before the events of A Fire upon the Deep, Pham Nuwen is living in anonymity among the Qeng Ho interstellar trading fleet.  In high orbit above the planet Arachna, they wait for the awakening of its dormant population, the Spiders, who have burrowed deep into the planet, awaiting the relighting of the On/Off star their planet orbits.  For when light returns, Arachna will at long last explode into a Golden Age of technology and commerce."],
    quote: { text: "The manhunt extended across more than one hundred light-years and eight centuries.", source: "First sentence" }
  },
  {
    id: "ol-OL1975714W",
    title: "A Fire upon the Deep",
    subtitle: "",
    author: "Vernor Vinge",
    year: 1992,
    genre: "Science Fiction",
    rating: 4.2,
    pages: 605,
    publisher: "GOLLANCZ",
    language: "English",
    isbn: "9782221125779",
    cover: "assets/covers/ol-OL1975714W.jpg",
    coverFrom: "#106025",
    coverTo: "#093414",
    tags: ["fiction", "hugo award winner", "life on other planets", "award:hugo_award=1993"],
    blurb: ["Thousands of years in the future, humanity is no longer alone in a universe where a mind's potential is determined by its location in space, from superintelligent entities in the Transcend, to the limited minds of the Unthinking Depths, where only simple creatures, and technology, can function. Nobody knows what strange force partitioned space into these \"regions of thought,\" but when the warring Straumli realm use an ancient Transcendent artifact as a weapon, they unwittingly unleash an awesome power that destroys thousands of worlds and enslaves all natural and artificial intelligence.", "Fleeing this galactic threat, Ravna crash lands on a strange world with a ship-hold full of cryogenically frozen children, the only survivors from a destroyed space-lab. They are taken captive by the Tines, an alien race with a harsh medieval culture, and used as pawns in a ruthless power struggle."],
    quote: { text: "The coldsleep itself was dreamless.", source: "First sentence" }
  },
  {
    id: "ol-OL17062642W",
    title: "Ancillary Sword",
    subtitle: "",
    author: "Ann Leckie",
    year: 2014,
    genre: "Science Fiction",
    rating: 3.9,
    pages: 416,
    publisher: "J'ai lu",
    language: "English",
    isbn: "1478987375",
    cover: "assets/covers/ol-OL17062642W.jpg",
    coverFrom: "#0d2163",
    coverTo: "#071236",
    tags: ["science fiction", "fiction", "quests (expeditions)", "revenge"],
    blurb: ["Breq is a soldier who used to be a warship. Once a weapon of conquest controlling thousands of minds, now she has only a single body and serves the emperor.", "With a new ship and a troublesome crew, Breq is ordered to go to the only place in the galaxy she would agree to go: to Athoek Station to protect the family of a lieutenant she once knew - a lieutenant she murdered in cold blood."],
    quote: { text: "“Considering the circumstances, you could use another lieutenant.”", source: "First sentence" }
  },
  {
    id: "ol-OL27254W",
    title: "Burning Chrome",
    subtitle: "",
    author: "William Gibson",
    year: 1986,
    genre: "Science Fiction",
    rating: 3.9,
    pages: 224,
    publisher: "Arbor House",
    language: "English",
    isbn: "8445070800",
    cover: "assets/covers/ol-OL27254W.jpg",
    coverFrom: "#0b665b",
    coverTo: "#063732",
    tags: ["science fiction", "american literature", "fiction", "virtual reality"],
    blurb: ["Burning Chrome collects Gibson's early short fiction from the late 70's and early 80's.", "Contents:\nPreface / by Bruce Sterling --\nJohnny Mnemonic --\nThe Gernsback continuum --\nFragments of a hologram rose --\nThe belonging kind / by John Shirley and William Gibson --\nHinterlands --\nRed star, winter orbit / by Bruce Sterling and William Gibson --\nNew Rose Hotel --\nThe winter market --\nDogfight / by Michael Swanwick and William Gibson --\nBurning chrome."],
    quote: { text: "I put the shotgun in an Adidas bag and padded it out with four pairs of tennis socks, not my style at all, but that was what I was aiming for: If they think you're crude, go technical; if they think you're technical, go crude.", source: "First sentence" }
  },
  {
    id: "ol-OL893508W",
    title: "Chapterhouse Dune",
    subtitle: "",
    author: "Frank Herbert",
    year: 1985,
    genre: "Science Fiction",
    rating: 3.9,
    pages: 495,
    publisher: "Orion Publishing Group, Limited",
    language: "English",
    isbn: "8497597702",
    cover: "assets/covers/ol-OL893508W.jpg",
    coverFrom: "#5a145d",
    coverTo: "#310b32",
    tags: ["dune (imaginary place)", "fiction", "science fiction", "literature"],
    blurb: ["The desert planet Arrakis, called Dune, has been destroyed. Now the Bene Gesserit, heirs to Dune's powers, have colonized a green world and are turning it into a desert, mile by scorched mile."],
    quote: { text: "When the ghola-baby was delivered from the first Bene Gesrit axlotl tank, mother Superior Darwi Odrade ordered a quiet celebration in her private dining room atop Central.", source: "First sentence" }
  },
  {
    id: "ol-OL3759348W",
    title: "A Savage Adoration",
    subtitle: "",
    author: "Penny Jordan",
    year: 1987,
    genre: "Thriller",
    rating: 3.6,
    pages: 220,
    publisher: "Bianca",
    language: "English",
    isbn: "9781842831922",
    cover: "assets/covers/ol-OL3759348W.jpg",
    coverFrom: "#5d630d",
    coverTo: "#333607",
    tags: ["fiction", "thriller"],
    blurb: ["Dominic acted as if nothing had happened.", "As though Christy's adolescent advances had not aroused his anger and contempt. The humiliation of his words had haunted her since and stood between her and all other men."],
    quote: null
  },
  {
    id: "ol-OL46900W",
    title: "Airframe",
    subtitle: "",
    author: "Michael Crichton",
    year: 1996,
    genre: "Thriller",
    rating: 3.7,
    pages: 431,
    publisher: "Knopf Doubleday Publishing Group",
    language: "Japanese",
    isbn: "075690627X",
    cover: "assets/covers/ol-OL46900W.jpg",
    coverFrom: "#6b066b",
    coverTo: "#3a033a",
    tags: ["air safety", "media relations", "type rating", "first officers"],
    blurb: ["Airframe is a novel by the American writer Michael Crichton, his eleventh under his own name and twenty-first overall, first published in 1996, in hardcover, by Knopf and then in 1997, as a paperback, by Ballantine Books. The plot follows Casey Singleton, a quality assurance vice president at the fictional aerospace manufacturer Norton Aircraft, as she investigates an in-flight accident aboard a Norton-manufactured airliner that leaves three passengers dead and 56 injured."],
    quote: { text: "\"Socal Approach, this is TransPacific 545.", source: "First sentence" }
  },
  {
    id: "ol-OL3931399W",
    title: "Bride of Pendoric",
    subtitle: "",
    author: "Eleanor Burford",
    year: 1963,
    genre: "Thriller",
    rating: 3.7,
    pages: 288,
    publisher: "Vergara Editor S.A.",
    language: "English",
    isbn: "9780613095396",
    cover: "assets/covers/ol-OL3931399W.jpg",
    coverFrom: "#12660a",
    coverTo: "#0a3805",
    tags: ["married people", "fiction", "suspense"],
    blurb: ["Favel Farrington meets Roc Pendorric on the idyllic Mediterranean island of Capri, where she was raised and lives with her father. Roc sweeps her off her feet, taking her from her home by an emerald sea to the ancient family home of the Pendorrics, in Cornwall. His sister and her family await them with open arms, welcoming young Favel. She is the much anticipated Bride of Pendorric, a name that amuses and flatters her.", "The castle is beautiful in its way, but the atmosphere is foreboding. Roc's twin nieces begin watching her carefully; even the stones in the courtyard seem to have eyes. On the walls hang portraits of two other Brides of Pendorric--one of them Roc's mother--who died both young and tragically. Favel's fear increases as Roc seems to be growing more and more distant. Has her courtship and marriage been just a deception?"],
    quote: null
  },
  {
    id: "ol-OL17864836W",
    title: "Cadáver exquisito",
    subtitle: "",
    author: "Agustina Bazterrica",
    year: 2015,
    genre: "Thriller",
    rating: 3.8,
    pages: 224,
    publisher: "clarin/alfaguara",
    language: "English",
    isbn: "9788366718357",
    cover: "assets/covers/ol-OL17864836W.jpg",
    coverFrom: "#225d13",
    coverTo: "#13330b",
    tags: ["romance literature", "fiction", "dystopias", "dystopies"],
    blurb: ["Working at the local processing plant, Marcos is in the business of slaughtering humans—though no one calls them that anymore.", "His wife has left him, his father is sinking into dementia, and Marcos tries not to think too hard about how he makes a living. After all, it happened so quickly. First, it was reported that an infectious virus has made all animal meat poisonous to humans. Then governments initiated the “Transition.” Now, eating human meat—“special meat”—is legal. Marcos tries to stick to numbers, consignments, processing."],
    quote: null
  },
  {
    id: "ol-OL2577480W",
    title: "Chrzest ognia",
    subtitle: "",
    author: "Andrzej Sapkowski",
    year: 1996,
    genre: "Thriller",
    rating: 4,
    pages: 348,
    publisher: "Orbit",
    language: "English",
    isbn: "9781473231108",
    cover: "assets/covers/ol-OL2577480W.jpg",
    coverFrom: "#650b25",
    coverTo: "#370614",
    tags: ["fiction", "heiresses", "magic", "monsters"],
    blurb: ["Nieustraszony pogromca potworów podąża tropem przeznaczonej mu dziewczynki. W świecie targanym krwawą wojną nie jest mu dane zachować neutralność.", "JASKIER, trubadur w kapelusiku z piórkiem egreta. Studiował siedem sztuk wyzwolonych, słynny po wszystkich dworach i zamtuzach. „Kłamliwa łajza” i „zachrypnięty bażant” to najłagodniejsze z określeń, jakim obdarzają go porzucone kochanki."],
    quote: null
  },
  {
    id: "ol-OL29195444W",
    title: "Corrupted Chaos",
    subtitle: "",
    author: "Shain Rose",
    year: 2022,
    genre: "Thriller",
    rating: 3.8,
    pages: 372,
    publisher: "Meredith Wild LLC",
    language: "English",
    isbn: "9781956810073",
    cover: "assets/covers/ol-OL29195444W.jpg",
    coverFrom: "#28650b",
    coverTo: "#163706",
    tags: ["fiction", "thriller"],
    blurb: ["My enemy doesn’t make the rules…\nEven if he’s my boss.", "Cade Armanelli might be an infamous hacker with billionaire status who operates better alone, but I earned my spot working alongside him...\nWhether he likes it or not."],
    quote: null
  },
  {
    id: "ol-OL38494W",
    title: "Cryptonomicon",
    subtitle: "",
    author: "Neal Stephenson",
    year: 1999,
    genre: "Thriller",
    rating: 4.5,
    pages: 918,
    publisher: "Perennial",
    language: "German",
    isbn: "9780060512804",
    cover: "assets/covers/ol-OL38494W.jpg",
    coverFrom: "#08682b",
    coverTo: "#043918",
    tags: ["fiction", "world war", "cryptography", "literature"],
    blurb: ["Neal Stephenson hacks into the secret histories of nations and the private obsessions of men, decrypting with dazzling virtuosity the forces that shaped this century.", "In 1942, Lawrence Pritchard Waterhouse - mathematical genius and young Captain in the US Navy - is assigned to Detachment 2702. It is an outfit so secret that only a handful of people know it exists, and some of those people have names like Churchill and Roosevelt. The mission of Watrehouse and Detachment 2702 - commanded by Marine Raider Bobby Shaftoe - is to keep the Nazis ignorant of the fact that Allied Intelligence has cracked the enemy's fabled Enigma code."],
    quote: { text: "IS THE BEST THAT CORPORAL BOBBY SHAFTOE CAN do on short notice-he's standing on the running board, gripping his Springfield with one hand and the rearview mirror with the other, so counting the syllables on his fingers is out of the question.", source: "First sentence" }
  },
  {
    id: "ol-OL3759289W",
    title: "Dangerous Interloper",
    subtitle: "",
    author: "Penny Jordan",
    year: 1991,
    genre: "Thriller",
    rating: null,
    pages: 192,
    publisher: "Harlequin",
    language: "English",
    isbn: "9781488057854",
    cover: "assets/covers/ol-OL3759289W.jpg",
    coverFrom: "#092867",
    coverTo: "#051638",
    tags: ["fiction", "suspense", "thriller"],
    blurb: ["Women as independent and career-minded as Miranda didn't just bump into a total stranger and fall in love. Ridiculous. Impossible. Totally unthinkable. There must have been some other more logical explanation for her extraordinary reaction to Ben Frobisher.", "The computer expert had already made quite an impact on the small English market town, and the fact that he'd reduced Miranda to a giddy teenager only fueled her determination to remain detached. True, she found him incredibly desirable, but did he have to invade her dreams every night? Did he have to reveal emotions and needs she had never before experienced?"],
    quote: null
  },
  {
    id: "ol-OL471500W",
    title: "4:50 from Paddington",
    subtitle: "",
    author: "Agatha Christie",
    year: 1957,
    genre: "Mystery",
    rating: 4,
    pages: 253,
    publisher: "The Book Club",
    language: "English",
    isbn: "157270229X",
    cover: "assets/covers/ol-OL471500W.jpg",
    coverFrom: "#556908",
    coverTo: "#2e3904",
    tags: ["fiction", "mystery", "marple", "english literature"],
    blurb: ["Agatha Christie’s audacious mystery thriller, reissued with a striking new cover designed to appeal to the latest generation of Agatha Christie fans and book lovers.", "For an instant the two trains ran together, side by side. In that frozen moment, Elspeth witnessed a murder. Helplessly, she stared out of her carriage window as a man remorselessly tightened his grip around a woman’s throat. The body crumpled. Then the other train drew away."],
    quote: { text: "Mrs. McGillicuddy panted along the platform in the wake of the porter carrying her suitcase.", source: "First sentence" }
  },
  {
    id: "ol-OL262496W",
    title: "A Study in Scarlet",
    subtitle: "",
    author: "Arthur Conan Doyle",
    year: 1887,
    genre: "Mystery",
    rating: 4,
    pages: 162,
    publisher: "Lulu.com",
    language: "English",
    isbn: "9798694645935",
    cover: "assets/covers/ol-OL262496W.jpg",
    coverFrom: "#0c6516",
    coverTo: "#06370c",
    tags: ["aortic aneurysm", "battle of maiwand", "blessing and cursing", "children's fiction"],
    blurb: ["A Study in Scarlet is an 1887 detective novel by British writer Arthur Conan Doyle. The story marks the first appearance of Sherlock Holmes and Dr. Watson, who would become the most famous detective duo in literature."],
    quote: { text: "IN the year 1878 I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the army.", source: "First sentence" }
  },
  {
    id: "ol-OL471943W",
    title: "After the Funeral",
    subtitle: "",
    author: "Agatha Christie",
    year: 1953,
    genre: "Mystery",
    rating: 4.2,
    pages: 237,
    publisher: "Turtleback Books",
    language: "English",
    isbn: "9780007493579",
    cover: "assets/covers/ol-OL471943W.jpg",
    coverFrom: "#581825",
    coverTo: "#300d14",
    tags: ["fiction", "mystery", "private investigators", "belgians"],
    blurb: ["When Cora is savagely murdered with a hatchet, the extraordinary remark she made the previous day at her brother Richard's funeral suddenly takes on a chilling significance. At the reading of Richard's will, Cora was clearly heard to say: 'It's been hushed up very nicely, hasn't it. But he was murdered, wasn't he?' In desperation, the family solicitor turns to Hercule Poirot to unravel the mystery."],
    quote: { text: "OLD Lanscombe moved totteringly from room to room, pulling up the blinds.", source: "First sentence" }
  },
  {
    id: "ol-OL471565W",
    title: "And Then There Were None",
    subtitle: "",
    author: "Agatha Christie",
    year: 1939,
    genre: "Mystery",
    rating: 4.3,
    pages: 222,
    publisher: "HarperAudio",
    language: "English",
    isbn: "9781533317926",
    cover: "assets/covers/ol-OL471565W.jpg",
    coverFrom: "#0a6643",
    coverTo: "#063824",
    tags: ["roman policier", "français (langue)", "cyanide poisoning", "chloral hydrate"],
    blurb: ["And Then There Were None is a mystery novel by the English writer Agatha Christie, described by her as the most difficult of her books to write. It was first published in the United Kingdom by the Collins Crime Club on 6 November 1939, as Ten Little Niggers, after the children's counting rhyme and minstrel song, which serves as a major element of the plot. A US edition was released in January 1940 with the title And Then There Were None, which is taken from the last five words of the song.", "In 1990 Crime Writers' Association ranked And Then There Were None 19th in their The Top 100 Crime Novels of All Time list. In 1995 in a similar list Mystery Writers of America ranked the novel 10th. In September 2015, to mark her 125th birthday, And Then There Were None was named the \"World's Favourite Christie\" in a vote sponsored by the author's estate. In the \"Binge!\" article of Entertainment Weekly Issue #1343-44 (26 December 2014–3 January 2015), the writers picked And Then There Were None as an \"EW favorite\" on the list of the \"Nine Great Christie Novels\"."],
    quote: { text: "IN THE CORNER of a first-class smoking carriage, Mr. Justice Wargrave, lately retired from the bench, puffed at a cigar and ran an interested eye through the political news in the Times.", source: "First sentence" }
  },
  {
    id: "ol-OL471667W",
    title: "Appointment with Death",
    subtitle: "",
    author: "Agatha Christie",
    year: 1938,
    genre: "Mystery",
    rating: 3.7,
    pages: 224,
    publisher: "Librairie des Champs-Elysees",
    language: "English",
    isbn: "270241351X",
    cover: "assets/covers/ol-OL471667W.jpg",
    coverFrom: "#5a1629",
    coverTo: "#310c16",
    tags: ["belgians", "belgians in fiction", "fiction", "fiction inenglish"],
    blurb: ["Agatha Christie set this book in Jerusalem. An english family headed by a bullying overbearing mother is murdered. Suspicion falls on members of the family, so Poirot steps in to investigate."],
    quote: { text: "\"YOU do see, don't you, that she's go to be killed?\"", source: "First sentence" }
  },
  {
    id: "ol-OL265415W",
    title: "At Bertram's Hotel",
    subtitle: "",
    author: "Agatha Christie",
    year: 1965,
    genre: "Mystery",
    rating: 4.1,
    pages: 248,
    publisher: "Librairie des Champs-Élysées",
    language: "French",
    isbn: "0063221624",
    cover: "assets/covers/ol-OL265415W.jpg",
    coverFrom: "#35610f",
    coverTo: "#1d3508",
    tags: ["fiction", "women detectives", "older women", "history"],
    blurb: ["An old-fashioned London Hotel is not quite as reputable as it makes out… When Miss Marple comes up from the country for a holiday in London, she finds what she’s looking for at Bertram’s Hotel: traditional decor, impeccable service and an unmistakable atmosphere of danger behind the highly polished veneer. Yet, not even Miss Marple can foresee the violent chain of events set in motion when an eccentric guest makes his way to the airport on the wrong day…"],
    quote: { text: "In the heart of the West End, there are many quiet pockets, unknown to almost all but taxi drivers who traverse them with expert knowledge, and arrive triumphantly thereby at Park Lane, Berkeley Square, or South Audley Street.", source: "First sentence" }
  },
  {
    id: "ol-OL28953746W",
    title: "Brain Damage",
    subtitle: "",
    author: "Freida McFadden",
    year: 2016,
    genre: "Mystery",
    rating: 4.2,
    pages: 392,
    publisher: "Independently Published",
    language: "English",
    isbn: "1532902948",
    cover: "assets/covers/ol-OL28953746W.jpg",
    coverFrom: "#104f60",
    coverTo: "#092b34",
    tags: ["american literature", "thriller", "mystery", "fiction"],
    blurb: ["After years of hard work, Dr. Charly McKenna finally has it all. Prosperous career as a dermatologist? Check. Spacious apartment overlooking Central Park? Check. Handsome lawyer husband? Double check.", "Then one night, a bullet rips through the right side of her skull and she loses everything."],
    quote: null
  },
  {
    id: "ol-OL471641W",
    title: "Cat Among the Pigeons",
    subtitle: "",
    author: "Agatha Christie",
    year: 1959,
    genre: "Mystery",
    rating: 4,
    pages: 256,
    publisher: "Collins [for] the Crime Club",
    language: "English",
    isbn: "8427285647",
    cover: "assets/covers/ol-OL471641W.jpg",
    coverFrom: "#0f5c62",
    coverTo: "#083235",
    tags: ["fiction", "mystery", "boarding schools", "private investigators"],
    blurb: ["E-book exclusive extras:1) Christie biographer Charles Osborne's essay on Cat Among the Pigeons;2) \"The Poirots\":  the complete guide to all the cases of the great Belgian detective.A revolution in the Middle East has a direct and deadly impact upon the summer term at Meadowbank, a picture-perfect girls’ school in the English countryside. Prince Ali Yusuf, Hereditary Sheikh of Ramat, whose great liberalizing experiment—‘hospitals, schools, a Health Service’—is coming to chaos, knows that he must prepare for the day of his exile."],
    quote: { text: "ABOUT two months earlier than the first day of the summer term at Meadowbank, certain events had taken place which were to have unexpected repercussions in that celebrated girls' school.", source: "First sentence" }
  },
  {
    id: "ol-OL21703979W",
    title: "A Court of Silver Flames",
    subtitle: "",
    author: "Sarah J. Maas",
    year: 2021,
    genre: "Fantasy",
    rating: 4.4,
    pages: 768,
    publisher: "Crossbooks",
    language: "English",
    isbn: "1526633469",
    cover: "assets/covers/ol-OL21703979W.jpg",
    coverFrom: "#106051",
    coverTo: "#09342c",
    tags: ["fiction", "women spies", "fairies", "magic"],
    blurb: ["Sarah J. Maas's sexy, richly imagined Court of Thorns and Roses series continues with the journey of Feyre's fiery sister, Nesta.", "Nesta Archeron has always been prickly – proud, swift to anger and slow to forgive. And since the war – since being made High Fae against her will – she's struggled to forget the horrors she endured and find a place for herself within the strange and deadly Night Court."],
    quote: { text: "Cassian raised his fist to the green door in the dim hallway—and hesitated.", source: "First sentence" }
  },
  {
    id: "ol-OL80870W",
    title: "A Spell for Chameleon",
    subtitle: "",
    author: "Piers Anthony",
    year: 1977,
    genre: "Fantasy",
    rating: 3.8,
    pages: 344,
    publisher: "Terra Fantastica",
    language: "Russian",
    isbn: "034525855X",
    cover: "assets/covers/ol-OL80870W.jpg",
    coverFrom: "#295d13",
    coverTo: "#16330a",
    tags: ["fiction", "fantasy", "magic"],
    blurb: ["Xanth was the enchanted land where magic ruled - where every citizen had a special spell only he could cast. It was a land of centaurs, dragons and basiliks.But poor Bink alone had no magic. And unless he got some - and fast - he would be exiled.", "The Good Magician Humfrey was convined that Bink did indeed have magic, magic as powerful as any possessed by the King or Good Magician Humfrey himself. But no one could fathom the nature of Bink's very special magic. Bink was in despair. This was worse than having no magic at all...and he would still be exiled."],
    quote: { text: "A small lizard perched on a brown stone.", source: "First sentence" }
  },
  {
    id: "ol-OL17770504W",
    title: "Arcanum Unbounded",
    subtitle: "The Cosmere Collection",
    author: "Brandon Sanderson",
    year: 2016,
    genre: "Fantasy",
    rating: 4.6,
    pages: 672,
    publisher: "Tor Fantasy",
    language: "English",
    isbn: "0765395649",
    cover: "assets/covers/ol-OL17770504W.jpg",
    coverFrom: "#5b3516",
    coverTo: "#311d0c",
    tags: ["fiction", "fantasy fiction", "fantasy"],
    blurb: ["The first story collection by New York Times bestselling author Brandon Sanderson", "Brandon Sanderson creates worlds, and those worlds are linked. His universe spans the Stormlight Archive, the Mistborn series, the tales of Elantris, and others, comprising a unique constellation of vividly imagined realms known as the Cosmere."],
    quote: null
  },
  {
    id: "ol-OL2707183W",
    title: "Assassin's Apprentice",
    subtitle: "",
    author: "Robin Hobb",
    year: 1995,
    genre: "Fantasy",
    rating: 3.9,
    pages: 400,
    publisher: "HarperCollins Publishers Limited",
    language: "English",
    isbn: "0008363730",
    cover: "assets/covers/ol-OL2707183W.jpg",
    coverFrom: "#62340e",
    coverTo: "#361c08",
    tags: ["fiction", "assassins", "the farseer trilogy", "fantasy"],
    blurb: ["Young Fitz is the bastard son of the noble Prince Chivalry, raised in the shadow of the royal court by his father's gruff stableman.  He is treated like an outcast by all the royalty except the devious King Shrewd, who has him secretly tutored in the arts of the assassin.  For in Fitz's blood runs the magic Skill--and the darker knowledge of a child raised with the stable hounds and rejected by his family.  As barbarous raiders ravage the coasts, Fitz is growing to manhood.  Soon he will face his first dangerous, soul-shattering mission."],
    quote: { text: "A HISTORY OF THE SIX Duchies is of necessity a history of its ruling family, the Farseers.", source: "First sentence" }
  }
];
